/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./import_frontend/**/*.{html,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00311f",
        "on-primary-fixed-variant": "#3323cc",
        "secondary": "#4edea3",
        "outline": "#918fa1",
        "on-primary-fixed": "#0f0069",
        "error": "#ffb4ab",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#ffd0d2",
        "error-container": "#93000a",
        "surface-container-lowest": "#060e20",
        "surface-tint": "#c3c0ff",
        "secondary-container": "#00a572",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "on-surface-variant": "#c7c4d8",
        "tertiary": "#ffb2b7",
        "on-secondary": "#003824",
        "on-secondary-fixed": "#002113",
        "on-background": "#dae2fd",
        "tertiary-fixed-dim": "#ffb2b7",
        "surface-bright": "#31394d",
        "surface": "#0b1326",
        "on-surface": "#dae2fd",
        "on-tertiary": "#67001b",
        "background": "#0b1326",
        "on-tertiary-fixed": "#40000d",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        "surface-container-low": "#131b2e",
        "on-primary": "#1d00a5",
        "on-secondary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-high": "#222a3d",
        "primary-container": "#4f46e5",
        "primary": "#c3c0ff",
        "outline-variant": "#464555",
        "surface-container-highest": "#2d3449",
        "tertiary-container": "#bf0f3c",
        "surface-dim": "#0b1326",
        "secondary-fixed": "#6ffbbe",
        "surface-container": "#171f33",
        "on-tertiary-fixed-variant": "#92002a",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "inverse-primary": "#4d44e3",
        "tertiary-fixed": "#ffdadb",
        "primary-fixed": "#e2dfff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "base": "4px",
        "xs": "4px",
        "xl": "40px",
        "md": "16px",
        "lg": "24px",
        "layout-margin": "32px",
        "layout-gutter": "20px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        "label-sm": ["Inter", "sans-serif"],
        "heading-md": ["Inter", "sans-serif"],
        "heading-lg": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "heading-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "heading-lg": ["30px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "data-mono": ["16px", { "lineHeight": "1", "fontWeight": "500" }],
        "display-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
