services:
  backend:
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_GRAPHQL_GRAPHIQL_ENABLED: "false"
      CORS_ALLOWED_ORIGINS: "https://walletpulse.de,https://www.walletpulse.de"

  frontend:
    ports:
      - "3000:80"
