services:
  db:
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    image: ghcr.io/wsukram/walletpulse-backend:latest
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CORS_ALLOWED_ORIGINS: "https://walletpulse.de,https://www.walletpulse.de,https://wsukram.github.io"

  frontend:
    image: ghcr.io/wsukram/walletpulse-frontend:latest
    ports:
      - "3000:80"
