services:
  db:
    ports: []

  backend:
    ports: []
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_GRAPHQL_GRAPHIQL_ENABLED: "false"

  frontend:
    ports:
      - "3000:80"
